### ISSUE TITLE
Gatsby precache impact login and redirect

### ISSUE THREAD

**Issue by hughcameron** [Trunkplatform/lpma#29]
Hey @gnunua - would you mind putting together some detail on the issue around Gatsby precaching and how it's affecting login and redirects?

I'm getting some support from our team to look into this.

It'd also be good to get an understanding of what information Netlify support has provided.

**Comment by gnunua** [comment]
Hey there. I did not get an answer from Netlify support team regarding redirect issues mentioned above. I have been implemented authentification using [aut0](https://auth0.com/).
