### ISSUE TITLE
Image Loading - Traced SVG Method

### ISSUE THREAD

**Issue by hughcameron** [Trunkplatform/lpma#35]
Hi @gnunua - we'd like to use the 'Traced SVG' method of image loading across the LPMA.COM site.

Here's the documentation on the Gatsby plugin: https://www.gatsbyjs.org/packages/gatsby-image/

Here's a demo of how it works: https://using-gatsby-image.gatsbyjs.org/traced-svg/

**Comment by gnunua** [comment]
Hey @hughcameron.
Image Optimization is easy with Gatsby.js using `traced SVG`'s or `blurred up` images techniue. 
I have implemented `blurred up` image optimization in [Image quality #18 ](https://github.com/Trunkplatform/lpma/issues/18) card. 
We can use image sharp processing such as `Traced SVG`  only with local assest. Unfortunaltly Contentful Images API did not support images sharp processing. I have contacted with their support tem and got the folowing answer:
![cont_screenshot at apr 06 18-11-33](https://user-images.githubusercontent.com/5013933/38425828-feef640a-39c5-11e8-943c-184a2be24387.png)

Please let me know your thoughts. Thanks.
