### ISSUE TITLE
Replicate lpma.com/events page

### ISSUE THREAD

**Issue by hughcameron** [Trunkplatform/lpma#40]
We'd like to use the content at http://www.lpma.com/events/ to populate https://lpma.netlify.com/events

Acceptance criteria:
- Links drive through to Eventbrite where relevant
- Content management is set up in Contentful

**Comment by gnunua** [comment]
Hi @mattyvent, @hughcameron.  LPMA 2018 Conference Series `learn more` button navigates to http://www.lpma.com/lpma2018conferenceseries/ page. 
We did not have lpma2018conferenceseries page with the new version.

**Comment by patmifsud** [comment]
@gnunua We'll add a card for this page. If the page isn't up when the website goes live we can have the button go through to the contact us page as we discussed

**Comment by gnunua** [comment]
Hey @patmifsud. Just for now just navigating to http://www.lpma.com/contact/. We have not new contact page.

**Comment by patmifsud** [comment]
Good point haha, i've carded it up.
For the time being please direct to href="mailto:justin@lpma.com" until the contact page card is completed
https://github.com/Trunkplatform/lpma/issues/49
