### ISSUE TITLE
Misc Changes and Tweaks

### ISSUE THREAD

**Issue by patmifsud** [Trunkplatform/lpma#52]
https://realtimeboard.com/app/board/o9J_kzpwbtU=/

We've gone through the website and picked out a couple of styling tweaks.

**All pages:**
Footer
- Remove 'building your business and building your career from the footer
- 25 pixels more spacing between the social icons and the 'Leading property managers association' bits
- only show 'Join LPMA' in the footer for logged out users (if this is easy enough to do)

Menu
- remove 'membership' and 'about' from the menu
- remove 'resources' for logged out users
- remove login for logged in users (if not removed already)
(applies to footer too) 

**Resources**
- images are squashed, not respecting the original proportions of the images
- contact us button should be moved up under the text

**Foundry**
- links on the foundry homepage for logged in users don't work (building a career and building your business) 
- remove 'was this helpful' from all pages other than guides
- remove .section container.foundry-heading on the foundry logged in home page
- Foundry logged out page, padding is missing from the sections under the picture of the  computer, please refer to the original wordpress page 

**Join us**
- add gaps between words in the form field 'firstGAPname'
- remove the entire "Leaders surround themselves..." section

**Events**
- remove '3' from the title of LPMA 20183

**Comment by gnunua** [comment]
Which version did you check?  Some issues I have fixed. 
Please go through https://dev-lpma.netlify.com/ version.

----
**Resources** 
- images are squashed, not respecting the original proportions of the images

1 - Not clear, how it should look like, Please provide more information.

---
**Foundry**
- remove .section container.foundry-heading on the foundry logged in home page
2 - Do you mean `HTML` elements?

---
**Foundry**
 - remove 'was this helpful' from all pages other than guides
3 - What about document suite pages?
---
**Foundry**
- Foundry logged out a page, padding is missing from the sections under the picture of the computer, please refer to the original WordPress page
4 - Can not find, Could you please make a screenshot
---
**Join us**
- remove the entire "Leaders surround themselves..." section
5 - Should I remove just text or full jumbotron ( with background)?
---
**Join us**
- add gaps between words in the form field 'firstGAPname'
6- not clear what you mean saying 'firstGAPname'
---

**Foundry**
- links on the foundry homepage for logged in users don't work (building a career and building your business)
7 - Did not find the issue.
---
** Footer **
- Remove 'building your business and building your career from the footer.
8 - Please provide  UI or at least some screenshots to figure out

**Comment by patmifsud** [comment]
Thanks Gnun

1- Exactly the same
2- The gap marked in red in the attached screenshot 
![screen shot 2018-03-26 at 8 10 39 am](https://user-images.githubusercontent.com/11660001/37879991-3987b196-30cd-11e8-854e-2bf983cb752f.png)
3- Yep, there aren't 'was this helpful' sections in the provided mocks.
4- Attached example. 
![screen shot 2018-03-26 at 8 13 47 am](https://user-images.githubusercontent.com/11660001/37880021-afb4bd78-30cd-11e8-91e9-e73fbc06adf2.png)
5- full jumbotron
6- sorry- i meant - fields have the placeholder 'firstname'. It should be 'first name' 
7 Attached screenshot - these links don't work on my end
![screen shot 2018-03-26 at 8 16 53 am](https://user-images.githubusercontent.com/11660001/37880048-1c500d98-30ce-11e8-90fc-c52921d8debe.png)
8 -  attached
![screen shot 2018-03-26 at 8 18 19 am](https://user-images.githubusercontent.com/11660001/37880055-45e93b02-30ce-11e8-9354-0ca5789e5a86.png)

**Comment by gnunua** [comment]
Hey @patmifsud. 
- 3- What about the "Privacy Policy", "Contact" and "Management Terms" pages? Could you please specify the exact pages where the "Was this helpful?" query should be placed on?  

- 4- I've searched out for the issue you mentioned, but I had trouble finding the missing padding on the foundry page. Could you please specify what setup did you check out the page (production build or development build)?
Here is the screenshot from https://dev-lpma.netlify.com/login-foundry
![image](https://user-images.githubusercontent.com/5013933/37979116-d562366e-31f8-11e8-9b28-21aebf6298a0.png)

**Comment by patmifsud** [comment]
3- remove from all pages other than pages which are guides.  e.g. this page should have a Was this helpful. https://dev-lpma.netlify.com/foundry/career-check-ins/career-check-ins  This page should not https://dev-lpma.netlify.com/foundry/getting-started 
4- Yep, looks like the issue has been fixed or I was in the wrong environment. Current page in the link you provided is fine. 
Thanks
