### ISSUE TITLE
Create a version of the document suite pages that are visible to logged out users

### ISSUE THREAD

**Issue by patmifsud** [Trunkplatform/lpma#58]
Hi Gnun,

We would like a way to send users a link to the document suite part of foundry even if they aren't logged into the website. Could we create a version of it that is hidden from everyone, but doesn't require login? 

Thanks

**Comment by gnunua** [comment]
Hey @patmifsud. 
- 1 - The document suite page consists of countries, which may have regions as their sub-routes, and the regions may have document lists (such as letters) as their sub-route. We have a trouble in understanding which links should be shareable to non-authenticated users.
- 2 - We assume that if we were to share the dropbox/downloadable links only, that can be done by just sending the link to a non-authenticated user.
- 3 - We would like to know how exactly the functionality should be implemented? Are there any examples available? For example, if we generate the shareable link, will the non-authenticated user be able to navigate through the website after visiting that link? Also, it would be great if you explain the format of the shareable links (for example, one way would be randomly generating the shareable links, hosting them somewhere and being able to share them with everyone.)
Thanks in advance.
